"""Ajout des modèles Etablissement et Demande

Revision ID: 5373cc167e5f
Revises: 9c21dad31316
Create Date: 2025-08-19 01:52:43.457231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5373cc167e5f'
down_revision = '9c21dad31316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etablissements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cecop', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['cecop'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etablissements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cecop')

    # ### end Alembic commands ###
