"""Création initiale de la base avec cascades

Revision ID: 8cd778171aed
Revises: 
Create Date: 2025-08-21 04:55:39.238993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd778171aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('cecop', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('processeur_id', sa.Integer(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['processeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandes_date_demande'), ['date_demande'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)

    op.create_table('ligne_demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_ecole', sa.String(length=50), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.Column('option', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ligne_demandes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))

    op.drop_table('notifications')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_timestamp'))

    op.drop_table('logs')
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_date_demande'))

    op.drop_table('demandes')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
