"""Ajout des modèles Etablissement et Demande

Revision ID: 9c21dad31316
Revises: 14adc4eb691c
Create Date: 2025-08-19 01:25:13.285994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c21dad31316'
down_revision = '14adc4eb691c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.Column('option', sa.String(length=100), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandes_date_demande'), ['date_demande'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etablissement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'etablissements', ['etablissement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etablissement_id')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_date_demande'))

    op.drop_table('demandes')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
