"""Ajout du modèle Notification

Revision ID: a26cadf939cd
Revises: 81a34f8d1d6e
Create Date: 2025-08-19 17:54:15.689341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26cadf939cd'
down_revision = '81a34f8d1d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processeur_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_traitement', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['processeur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_traitement')
        batch_op.drop_column('processeur_id')

    # ### end Alembic commands ###
