"""Ajout des modèles Etablissement et Demande

Revision ID: ef181d2d940b
Revises: 5373cc167e5f
Create Date: 2025-08-19 03:16:00.349437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef181d2d940b'
down_revision = '5373cc167e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligne_demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_ecole', sa.String(length=50), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.Column('option', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_column('option')
        batch_op.drop_column('niveau')
        batch_op.drop_column('quantite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('niveau', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('option', mysql.VARCHAR(length=100), nullable=False))

    op.drop_table('ligne_demandes')
    # ### end Alembic commands ###
